# *Kapitel 2 - Koduppgifter*

## **8. Förklara vad koden nedan gör. Varför är det viktigt att kunna spara en modell?**

Koden börjar med att importera make_regression, LinearRegression samt dump och load från joblib. make_regression används för att skapa ett artificiellt regressionsdataset som vi kan träna en modell på.

När `X, y = make_regression(n_samples=20000, n_features=3, noise=0.1)` körs skapas data med 20 000 observationer och tre features. X innehåller indata och y innehåller värdena som modellen ska lära sig att förutsäga.

Sedan skapas och tränas en linjär regressionsmodell med `LinearRegression().fit(X, y)`. Efter fit() har modellen lärt sig sina parametrar från datan.

Med `dump(model, "linear_model.joblib")` sparas den tränade modellen i en fil. Vi behöver då inte träna modellen från början varje gång vi vill använda den.

Med `model_loaded = load("linear_model.joblib")` läser vi tillbaka modellen från filen. Den laddade modellen kan sedan användas igen.

Till sist används `model_loaded.predict(X[:5])` för att göra prediktioner på de fem första observationerna. Poängen är att prediktionerna görs med den sparade och laddade modellen.

Att kunna spara en modell är viktigt i ett riktigt ML-projekt eftersom träning kan ta tid och modellen ofta behöver användas senare i exempelvis en applikation eller ett API. Man tränar därför modellen, sparar den och laddar den när den behövs.

Det är också en viktig del av att produktionssätta en modell, eftersom den tränade modellen behöver kunna användas utanför själva utvecklingsnotebooken.

In [94]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from joblib import dump, load

In [95]:
X, y = make_regression(n_samples=20000, n_features=3, noise=0.1)
model = LinearRegression().fit(X, y)
dump(model, "linear_model.joblib")
model_loaded = load("linear_model.joblib")
print(model_loaded.predict(X[:5]))

[-132.10981921  220.02694867  -93.6362765   -93.65212844 -105.07014612]

## **9. data_01.csv**

In [96]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import root_mean_squared_error

### **Load data**

In [97]:
# a) Läs in datasetet
df = pd.read_csv("dataset/data_01.csv")

In [98]:
df.head()

         x1        x2        x3        x4        x5      target
0  0.743487  1.072825  1.332911 -1.244771  0.344978  220.173943
1  0.835264  0.202184  0.966480  0.745883 -0.033773  175.873929
2 -1.103234  0.030615 -0.140385  0.727683 -2.831224 -162.270054
3  1.210186  1.685258 -0.394123  0.719024 -2.166585  165.930461
4  0.474577  0.647737 -0.451812 -0.409472 -0.051473   43.250511

#### **Define Features and Target**

In [99]:
# b) Dela upp datasetet i X och y

X = df.drop(columns="target")
y = df["target"]

In [100]:
X.head()

         x1        x2        x3        x4        x5
0  0.743487  1.072825  1.332911 -1.244771  0.344978
1  0.835264  0.202184  0.966480  0.745883 -0.033773
2 -1.103234  0.030615 -0.140385  0.727683 -2.831224
3  1.210186  1.685258 -0.394123  0.719024 -2.166585
4  0.474577  0.647737 -0.451812 -0.409472 -0.051473

In [101]:
y.head()

0    220.173943
1    175.873929
2   -162.270054
3    165.930461
4     43.250511
Name: target, dtype: float64

#### **Train, Validation and Test Split**

In [102]:
# c) Dela upp datasetet i tränings, validerings och testdata

X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.15, random_state=42)

print("Träningsdata:", X_train.shape)
print("Valideringsdata:", X_val.shape)
print("Testdata:", X_test.shape)

Träningsdata: (135, 5)
Valideringsdata: (24, 5)
Testdata: (40, 5)

#### **Train Regression Models**

In [103]:
# d) Träna två regressionsmodeller

linreg = LinearRegression()
tree = DecisionTreeRegressor(random_state=42)

linreg.fit(X_train, y_train)
tree.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

#### **Evaluate Models**

In [104]:
# e) Utvärdera modellerna på valideringsdatan

linreg_pred = linreg.predict(X_val)
tree_pred = tree.predict(X_val)

linreg_rmse = root_mean_squared_error(
    y_val,
    linreg_pred
)

tree_rmse = root_mean_squared_error(
    y_val,
    tree_pred
)

print("RMSE Linear Regression:", linreg_rmse)
print("RMSE Decision Tree:", tree_rmse)

RMSE Linear Regression: 3.592300959691065
RMSE Decision Tree: 99.3594190386419

#### **Select the Best Model**

In [105]:
# f) + g) Välj den bästa modellen och träna om på träning och valideringsdatan

if linreg_rmse < tree_rmse:
    best_model = LinearRegression()
    best_model_name = "Linear Regression"
else:
    best_model = DecisionTreeRegressor(random_state=42)
    best_model_name = "Decision Tree"

print("Best model:", best_model_name)

Best model: Linear Regression

#### **Retrain on Training and Validation Data**

In [106]:
best_model.fit(X_train_full, y_train_full)

LinearRegression()

#### **Final Test Evaluation**

In [107]:
test_pred = best_model.predict(X_test)

test_rmse = root_mean_squared_error(
    y_test,
    test_pred
)

print("Final Test RMSE:", test_rmse)

Final Test RMSE: 3.371549077515551

#### **Train Final Model on the Full Dataset**

In [108]:
# h) Träna modellen på hela datasetet
best_model.fit(X, y)

LinearRegression()

## **10. Datasetet salary_dataset.csv**

In [109]:
import pandas as pd

from sklearn.model_selection import train_test_split, cross_validate
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import root_mean_squared_error

### **Load data**

In [110]:
# a) Läs in datasetet

df = pd.read_csv("dataset/salary_dataset.csv")

### **Define features and target**

In [111]:
# a) Läs in datasetet och dela upp i X och y

X = df[["YearsExperience"]]
y = df["Salary"]

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
   YearsExperience
0              1.2
1              1.4
2              1.6
3              2.1
4              2.3

Target:
0    39344.0
1    46206.0
2    37732.0
3    43526.0
4    39892.0
Name: Salary, dtype: float64

### **Train-Test Split**

In [112]:
# b) Dela upp datan i tränings- och testdata

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training data:", X_train.shape)
print("Test data:", X_test.shape)

Training data: (24, 1)
Test data: (6, 1)

### **Cross-Validation**

In [113]:
# c) Träna två regressionsmodeller med 5-delad korsvalidering

linreg = LinearRegression()

tree = DecisionTreeRegressor(
    max_depth=3,
    random_state=42
)

linreg_cv = cross_validate(
    linreg,
    X_train,
    y_train,
    scoring="neg_root_mean_squared_error",
    cv=5
)

tree_cv = cross_validate(
    tree,
    X_train,
    y_train,
    scoring="neg_root_mean_squared_error",
    cv=5
)

### **Compare Models**

In [114]:
linreg_rmse = -linreg_cv["test_score"].mean()
tree_rmse = -tree_cv["test_score"].mean()

print("Linear Regression CV RMSE:", linreg_rmse)
print("Decision Tree CV RMSE:", tree_rmse)

Linear Regression CV RMSE: 5293.203196998775
Decision Tree CV RMSE: 6193.398440883071

### **Select the Best Model**

In [115]:
if linreg_rmse < tree_rmse:
    best_model = linreg
    best_model_name = "Linear Regression"
else:
    best_model = tree
    best_model_name = "Decision Tree"

print("Best model:", best_model_name)

Best model: Linear Regression

### **Final Test Evaluation**

In [116]:
# d) Välj den bästa modellen och utvärdera den på testdata
best_model.fit(X_train, y_train)

pred = best_model.predict(X_test)

test_rmse = root_mean_squared_error(
    y_test,
    pred
)

print("Best model:", best_model_name)
print("Test RMSE:", test_rmse)

Best model: Linear Regression
Test RMSE: 7059.043621901506

### **Analysis**

Linear Regression fick ett lägre RMSE än Decision Tree vid den 5-delade korsvalideringen. Därför valdes Linear Regression som den bäst presterande modellen.

Vid den slutliga utvärderingen på testdatan fick modellen ett RMSE på cirka 7059. Det innebär att modellens prediktioner i genomsnitt har ett fel på ungefär 7059 löneenheter på testdatan.

Resultaten visar att sambandet mellan `YearsExperience` och `Salary` i detta dataset kan modelleras relativt väl med en linjär modell.

## **11. Datasetet mpg**

In [117]:
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error

### **Load data**

In [118]:
# a) Läs in datasetet

df = sns.load_dataset("mpg")

In [119]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

### **Handle missing values**

In [120]:
# b) Droppa rader med saknade värden

df = df.dropna()

### **Remove the name column**

In [121]:
# c) Droppa kolumnen name

df = df.drop(columns="name")

### **Encode categorical data**

In [122]:
# d) Utför dummy-variable-encoding på origin

df = pd.get_dummies(df, columns=["origin"], drop_first=True)

In [123]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin_japan,origin_usa
0,18.0,8,307.0,130.0,3504,12.0,70,False,True
1,15.0,8,350.0,165.0,3693,11.5,70,False,True
2,18.0,8,318.0,150.0,3436,11.0,70,False,True
3,16.0,8,304.0,150.0,3433,12.0,70,False,True
4,17.0,8,302.0,140.0,3449,10.5,70,False,True

### **Define features and target**

In [124]:
# e) Dela upp datasetet i X och y

X = df.drop(columns="mpg")
y = df["mpg"]

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
   cylinders  displacement  horsepower  weight  acceleration  model_year  \
0          8         307.0       130.0    3504          12.0          70
1          8         350.0       165.0    3693          11.5          70
2          8         318.0       150.0    3436          11.0          70
3          8         304.0       150.0    3433          12.0          70
4          8         302.0       140.0    3449          10.5          70

   origin_japan  origin_usa
0         False        True
1         False        True
2         False        True
3         False        True
4         False        True

Target:
0    18.0
1    15.0
2    18.0
3    16.0
4    17.0
Name: mpg, dtype: float64

### **Train-Test Split**

In [125]:
# f) Dela upp datasetet i tränings och testdata
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

print("Training data:", X_train.shape)
print("Test data:", X_test.shape)

Training data: (313, 8)
Test data: (79, 8)

### **Train linear regression**

In [126]:
# g) Träna en linjär regressionsmodell på träningsdatan

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

### **Evaluate the model**

In [127]:
pred = model.predict(X_test)

rmse = root_mean_squared_error(
    y_test,
    pred
)

print("Test RMSE:", rmse)

Test RMSE: 3.256114096847396

### Analysis

Modellen tränades med de numeriska variablerna samt de två dummy-variablerna för `origin`. På testdatan fick modellen ett RMSE på cirka 3,26.

Det innebär att modellens prediktioner i genomsnitt har ett fel på ungefär 3,26 mpg. Resultatet visar att en linjär regressionsmodell kan användas för att förutsäga bränsleeffektiviteten utifrån de variabler som finns i datasetet.

## **12 – Förbättra Random Forest Regression på huspriser**

In [128]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error

### **Load data**

In [129]:
df = pd.read_csv("dataset/housing.csv")

In [130]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

### **Prepare data**

In [131]:
housing = pd.get_dummies(df, columns=["ocean_proximity"], drop_first=True)

In [132]:
X = housing.drop(columns=["median_house_value"])
y = housing["median_house_value"]

### **Train, Validation and Test Split**

In [133]:
X_train_full, X_test, y_train_full, y_test = train_test_split(
    X, y, test_size=0.2, random_state=40
)

X_train, X_val, y_train, y_val = train_test_split(
    X_train_full, y_train_full, test_size=0.25, random_state=36
)

### **Handle Missing Values**

In [134]:
imputer = SimpleImputer(strategy="median")

X_train_imputed = imputer.fit_transform(X_train)
X_val_imputed = imputer.transform(X_val)

### **Baseline Model**

In [135]:
baseline_model = RandomForestRegressor(random_state=42)

baseline_model.fit(X_train_imputed, y_train)
baseline_pred = baseline_model.predict(X_val_imputed)
baseline_rmse = root_mean_squared_error(y_val, baseline_pred)

print("Baseline Random Forest RMSE:", baseline_rmse)

Baseline Random Forest RMSE: 49767.88256564688

### **Feature Selection**

In [136]:
X_train_selected = X_train.drop(columns=["housing_median_age"])
X_val_selected = X_val.drop(columns=["housing_median_age"])
X_test_selected = X_test.drop(columns=["housing_median_age"])

In [137]:
selected_imputer = SimpleImputer(strategy="median")

X_train_selected = selected_imputer.fit_transform(X_train_selected)
X_val_selected = selected_imputer.transform(X_val_selected)
X_test_selected = selected_imputer.transform(X_test_selected)

#### **Random Forest with Feature Selection**

In [138]:
selected_model = RandomForestRegressor(n_estimators=100, random_state=42)

selected_model.fit(X_train_selected, y_train)
selected_pred = selected_model.predict(X_val_selected)
selected_rmse = root_mean_squared_error(y_val, selected_pred)

print("Random Forest with Feature Selection RMSE:", selected_rmse)

Random Forest with Feature Selection RMSE: 48868.11349669982

### **Hyperparameter Experiment**

In [139]:
tuned_model = RandomForestRegressor(n_estimators=300, random_state=42)

tuned_model.fit(X_train_selected, y_train)
tuned_pred = tuned_model.predict(X_val_selected)
tuned_rmse = root_mean_squared_error(y_val, tuned_pred)

print("Random Forest with Feature Selection and 300 Trees RMSE:", tuned_rmse)

Random Forest with Feature Selection and 300 Trees RMSE: 48801.580560923874

### **Model Comparison**

In [140]:
results = pd.DataFrame(
    {
        "Model": [
            "Baseline Random Forest",
            "Random Forest + Feature Selection",
            "Random Forest + Feature Selection + 300 Trees",
        ],
        "RMSE": [baseline_rmse, selected_rmse, tuned_rmse],
    }
)

results

                                           Model          RMSE
0                         Baseline Random Forest  49767.882566
1              Random Forest + Feature Selection  48868.113497
2  Random Forest + Feature Selection + 300 Trees  48801.580561

### **Final Model Evaluation**

In [141]:
final_model = RandomForestRegressor(n_estimators=300, random_state=42)

X_train_full_selected = X_train_full.drop(columns=["housing_median_age"])
X_test_selected = X_test.drop(columns=["housing_median_age"])

final_imputer = SimpleImputer(strategy="median")

X_train_full_selected = final_imputer.fit_transform(X_train_full_selected)
X_test_selected = final_imputer.transform(X_test_selected)

final_model.fit(X_train_full_selected, y_train_full)
final_pred = final_model.predict(X_test_selected)
final_rmse = root_mean_squared_error(y_test, final_pred)

print("Final Model RMSE on Test Data:", final_rmse)

Final Model RMSE on Test Data: 50048.13040650423

### **Analysis**

Jag började med en Random Forest-modell som baseline och använde samma typ av train-, validation- och testuppdelning som i bokens kodexempel. Baseline-modellen gav ett RMSE på cirka 49 768 på valideringsdatan.

Därefter testade jag variabelselektion genom att ta bort `housing_median_age`. Detta gav ett RMSE på cirka 48 868, vilket var en förbättring jämfört med baseline-modellen.

Jag testade sedan att öka antalet träd i Random Forest från standardinställningen till 300 träd. Tillsammans med variabelselektionen gav detta ett RMSE på cirka 48 802 på valideringsdatan.

Resultaten visar att både variabelselektionen och ökningen av antalet träd förbättrade resultatet på valideringsdatan i dessa experiment. Förbättringen från 100 till 300 träd var däremot relativt liten, vilket visar att fler träd inte automatiskt ger en stor förbättring.

Den slutliga modellen tränades därefter på träningsdatan och utvärderades på den separata testdatan. Modellen fick ett RMSE på cirka 50 048 på testdatan.